spring:
  h2:
    console:
      enabled: true
      path: /h2console
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driverClassName: org.h2.Driver

google:
  client-id: ENC(GAmBuplLJtbDCjC+Oh7Uc/G47mIIyQ3wBttYN6O4NKMcZDueOD2/KkFY9uJmodX0zy2d8bZGizXrhHsGPaNFxleowKey9OEd6b8Mxk2shW2p7J7CvwGYig==)
  client-secret: ENC(N/7LNG2jkRJND9yIdGyux28F3AjOeQBfAhoGkdGK1yb2KK5lPBzZ4g==)
  redirect-uri: http://localhost:8080/api/todos/syncWithGoogleTasks
security:
  jwt:
    token:
      secret-key: secret

springfox:
  documentation:
    swagger-ui:
      base-url: /api

logging:
  level:
    root: debug

mail:
  templates.path: thymeleaf-templates
  host: SMTP.office365.com
  username: ENC(w+rbJUK0PHMuq5bRexiHD/r2P36/pr/FxhaZKII9vjQ=)
  password: ENC(8mN5EswTrJxk3Jva3fbv7QChxM9j0g+9)
  port: 587